# Generated by Django 4.2.16 on 2026-03-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('armazem', '0001_initial'),
        ('planeamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('planeamento', 'Em Planeamento'), ('em_producao', 'Em Produção'), ('pausada', 'Pausada'), ('qualidade', 'Em Controlo de Qualidade'), ('expedicao', 'Em Expedição'), ('montagem', 'Em Montagem'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planeamento', max_length=15)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('data_prevista_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_fim', models.DateField(blank=True, null=True)),
                ('data_real_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_real_fim', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='planeamento.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_criadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'ordering': ['-data_entrega_prevista', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos', to='producao.ordemproducao')),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Produção',
                'verbose_name_plural': 'Registos de Produção',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concluido', models.BooleanField(default=False)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='armazem.material')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Item de Produção',
                'verbose_name_plural': 'Itens de Produção',
            },
        ),
    ]
