# Generated by Django 4.2.16 on 2026-03-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0002_pedido_material_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descricao do problema')),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Analise'), ('resolvido', 'Resolvido')], default='pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.TextField(blank=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_assistencia', to='producao.ordemproducao')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistencias_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Assistencia',
                'verbose_name_plural': 'Pedidos de Assistencia',
                'ordering': ['-criado_em'],
            },
        ),
    ]
