# Generated by Django 4.2.16 on 2026-04-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0001_initial'),
        ('producao', '0004_data_planeamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='planeamento.cliente'),
        ),
    ]
