# Generated by Django 4.2.16 on 2026-04-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_ordemproducao_ficheiro_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheiroTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.FileField(upload_to='tecnicos/')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('carregado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='producao.ordemproducao')),
            ],
            options={
                'ordering': ['carregado_em'],
            },
        ),
    ]
