# Generated by Django 4.2.16 on 2026-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_pedidoassistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='data_planeamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Planeamento'),
        ),
    ]
