# Generated by Django 4.2.16 on 2026-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_alter_ordemproducao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='ficheiro_tecnico',
            field=models.FileField(blank=True, null=True, upload_to='tecnicos/'),
        ),
    ]
