# Generated by Django 4.2.16 on 2026-04-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_ficheirotecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='ficheiro_tecnico',
        ),
    ]
