# Generated by Django 4.2.16 on 2026-03-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaMontagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_curso', 'Em Curso'), ('concluida', 'Concluída'), ('problema', 'Com Problema')], default='pendente', max_length=10)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_montagem', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_montagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de Montagem',
                'verbose_name_plural': 'Tarefas de Montagem',
                'ordering': ['data_prevista', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='RegistoMontagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='montagem/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos', to='montagem.tarefamontagem')),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Montagem',
                'verbose_name_plural': 'Registos de Montagem',
                'ordering': ['-data'],
            },
        ),
    ]
