# Generated by Django 4.2.16 on 2026-03-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='NIF')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabalhadores/')),
                ('data_admissao', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('efetivo', 'Efetivo'), ('termo_certo', 'A Termo Certo'), ('termo_incerto', 'A Termo Incerto'), ('estagio', 'Estágio'), ('recibos_verdes', 'Recibos Verdes')], default='efetivo', max_length=20)),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'De Férias'), ('baixa', 'De Baixa')], default='ativo', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhadores', to='core.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhadores', to='core.departamento')),
                ('utilizador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabalhador',
                'verbose_name_plural': 'Trabalhadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AusenciaFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ferias', 'Férias'), ('falta_justificada', 'Falta Justificada'), ('falta_injustificada', 'Falta Injustificada'), ('baixa_medica', 'Baixa Médica'), ('licenca', 'Licença')], max_length=25)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='rh.trabalhador')),
            ],
            options={
                'verbose_name': 'Ausência / Falta',
                'verbose_name_plural': 'Ausências / Faltas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
