# Generated by Django 4.2.16 on 2026-03-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aprovado_condicional', 'Aprovado Condicionalmente')], max_length=25)),
                ('observacoes', models.TextField(blank=True)),
                ('nao_conformidades', models.TextField(blank=True, verbose_name='Não Conformidades')),
                ('acoes_corretivas', models.TextField(blank=True, verbose_name='Ações Corretivas')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Inspeção de Qualidade',
                'verbose_name_plural': 'Inspeções de Qualidade',
                'ordering': ['-data'],
            },
        ),
    ]
