# Generated by Django 4.2.16 on 2026-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecaoqualidade',
            name='tipo',
            field=models.CharField(choices=[('intermedia', 'Intermédia'), ('final', 'Final')], default='final', max_length=12),
        ),
    ]
