# Generated by Django 4.2.16 on 2026-03-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_preparacao', 'Em Preparação'), ('pronta', 'Pronta para Envio'), ('enviada', 'Enviada'), ('entregue', 'Entregue')], default='pendente', max_length=15)),
                ('data_prevista_envio', models.DateField(blank=True, null=True)),
                ('data_real_envio', models.DateTimeField(blank=True, null=True)),
                ('transportadora', models.CharField(blank=True, max_length=100)),
                ('guia_transporte', models.CharField(blank=True, max_length=100)),
                ('morada_entrega', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedicoes', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expedição',
                'verbose_name_plural': 'Expedições',
                'ordering': ['-criado_em'],
            },
        ),
    ]
