# Generated by Django 4.2.16 on 2026-03-13 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('armazem', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(editable=False, max_length=30, unique=True)),
                ('fornecedor', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('enviado', 'Enviado ao Fornecedor'), ('parcialmente_recebido', 'Parcialmente Recebido'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=30)),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='armazem.material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='armazem.pedidocompra')),
            ],
            options={
                'verbose_name': 'Item de Pedido de Compra',
                'verbose_name_plural': 'Itens de Pedido de Compra',
            },
        ),
    ]
