# Generated by Django 4.2.16 on 2026-04-14 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_cache', models.CharField(blank=True, max_length=150)),
                ('acao', models.CharField(choices=[('login', 'Login'), ('login_falhado', 'Login Falhado'), ('logout', 'Logout'), ('criacao', 'Criação'), ('edicao', 'Edição'), ('eliminacao', 'Eliminação'), ('mudanca_estado', 'Mudança de Estado'), ('mudanca_permissao', 'Mudança de Permissão'), ('movimento_stock', 'Movimento de Stock'), ('acao_admin', 'Ação Administrativa'), ('acesso_negado', 'Acesso Negado'), ('erro', 'Erro'), ('outro', 'Outro')], db_index=True, max_length=25)),
                ('modulo', models.CharField(blank=True, db_index=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('endpoint', models.CharField(blank=True, max_length=300)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['utilizador', '-timestamp'], name='auditoria_a_utiliza_6c9385_idx'), models.Index(fields=['acao', '-timestamp'], name='auditoria_a_acao_b6a1ad_idx'), models.Index(fields=['modulo', '-timestamp'], name='auditoria_a_modulo_9e7c26_idx')],
            },
        ),
    ]
